# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inspect.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inspect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinspect.proto\x12\x08\x61gentbox\"@\n\x0eInspectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\"E\n\x0fInspectResponse\x12\x0f\n\x07verdict\x18\x01 \x01(\t\x12\x0f\n\x07reasons\x18\x02 \x03(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t2K\n\tInspector\x12>\n\x07Inspect\x12\x18.agentbox.InspectRequest\x1a\x19.agentbox.InspectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inspect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSPECTREQUEST']._serialized_start=27
  _globals['_INSPECTREQUEST']._serialized_end=91
  _globals['_INSPECTRESPONSE']._serialized_start=93
  _globals['_INSPECTRESPONSE']._serialized_end=162
  _globals['_INSPECTOR']._serialized_start=164
  _globals['_INSPECTOR']._serialized_end=239
# @@protoc_insertion_point(module_scope)
